# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026 Sasha Levin <sashal@kernel.org>
TEST_GEN_PROGS := cve_31431_test
TEST_PROGS := killswitch_test.sh

CFLAGS += -O2 -g -std=gnu99 -Wall $(KHDR_INCLUDES)

include ../lib.mk
