#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# generate_api_specs.sh - Generate C file that includes all API specification headers
#
# Usage: generate_api_specs.sh <srctree> <objtree>

SRCTREE="$1"
OBJTREE="$2"

if [ -z "$SRCTREE" ] || [ -z "$OBJTREE" ]; then
    echo "Usage: $0 <srctree> <objtree>" >&2
    exit 1
fi

# Generate header
cat <<EOF
/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Auto-generated file - DO NOT EDIT
 * Generated by: scripts/generate_api_specs.sh
 *
 * This file includes all kernel API specification headers
 */

#include <linux/kernel.h>
#include <linux/kernel_api_spec.h>
#include <linux/errno.h>
#include <linux/capability.h>
#include <linux/fcntl.h>
#include <uapi/linux/aio_abi.h>
#include <uapi/linux/sched/types.h>
#include <uapi/linux/xattr.h>
#include <linux/eventfd.h>
#include <linux/eventpoll.h>
#include <linux/wait.h>
#include <linux/inotify.h>
#include <linux/splice.h>
#include <linux/timerfd.h>
#include <linux/kexec.h>
#include <uapi/linux/mount.h>
#include <uapi/linux/signalfd.h>
#include <linux/fs.h>
#include <linux/signal.h>
#include <linux/ptrace.h>
#include <linux/quota.h>
#include <linux/uio.h>
#include <linux/time.h>

#ifdef CONFIG_KAPI_SPEC

EOF

# Find all .apispec.h files and generate includes
# Look in both source tree and object tree
(find "$SRCTREE" -name "*.apispec.h" -type f 2>/dev/null; \
 find "$OBJTREE" -name "*.apispec.h" -type f 2>/dev/null) | \
    grep -v "/generated_api_specs.c" | \
    sort -u | \
    while read -r apispec_file; do
        # Get relative path from srctree or objtree
        case "$apispec_file" in
            "$SRCTREE"*)
                rel_path="${apispec_file#$SRCTREE/}"
                ;;
            *)
                rel_path="${apispec_file#$OBJTREE/}"
                ;;
        esac

        # Skip if file is empty
        if [ ! -s "$apispec_file" ]; then
            continue
        fi

        # Generate include statement with relative path from kernel/api/
        # The generated file is always at kernel/api/generated_api_specs.c,
        # so we need to go up two directories to reach the root
        echo "#include \"../../${rel_path}\""
    done

# Close the ifdef
cat <<EOF

#endif /* CONFIG_KAPI_SPEC */
EOF

