#
# Makefile for MStar pnl cust functions
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/pnl_cust
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include/sys/common
# specific options
EXTRA_CFLAGS      +=

# files
obj-y                       += mdrv_pnl_cust.o

mdrv-pnl-cust-objs          += mdrv_pnl_cust.o
